export enum CollectionService {
  CATEGORIES = 'categories',
  ITEMS = 'items',
}

export enum KeyService {
  // auth
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  LOGOUT = 'LOGOUT',
  LOGIN_WITH_PHONE = 'LOGIN_WITH_PHONE',
  CONFIRM_OTP = 'CONFIRM_OTP',

  // users
  LIST_USERS = 'LIST_USERS',

  // categories
  GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES',
  GET_ALL_CATEGORIES_WITH_ITEMS = 'GET_ALL_CATEGORIES_WITH_ITEMS',
  ADD_CATEGORY = 'ADD_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  EDIT_CATEGORY = 'EDIT_CATEGORY',
  GET_CATEGORY = 'GET_CATEGORY',

  // items
  GET_ALL_ITEMS = 'GET_ALL_ITEMS',
}
